# Generated by Django 3.2.8 on 2022-10-14 10:09
import os
from django.db import migrations
from music_jam.jams.models import User

users = [
    {
        "email": os.environ.get('defaul_superuser_username', 'admin@admin.com'),
        "password": os.environ.get('defaul_superuser_password', 'admin'),
        "is_staff": False,
        "is_superuser": False,
        "is_active": True
    },
    {
        "email": os.environ.get('defaul_defauluser_username', 'test@test.com'),
        "password": os.environ.get('defaul_defauluser_password', 'test'),
        "is_staff": True,
        "is_superuser": True,
        "is_active": True
    }


]


def populate(apps, schema_editor):
    for user in users:
        if user["is_superuser"]:
            User.objects.create_superuser(**user)
        else:
            User.objects.create_user(**user)


def reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("jams", "0001_initial"),
    ]

    operations = [migrations.RunPython(populate, reverse)]
