# Generated by Django 3.2.8 on 2022-10-14 10:09
import os
import random

from django.db import migrations

from music_jam.jams.models import User
from music_jam.jams.models import MusicJam
from music_jam.jams.models import MusicJamRole
from music_jam.jams.models import MusicRole

roles = [
    {
        "instrument": "Piano",
        "description": "Piano player"
    },
    {
        "instrument": "Flute",
        "description": "Flute player"
    },
    {
        "instrument": "Veena",
        "description": "Veena player"
    },
    {
        "instrument": "Bugle",
        "description": "Bugle player"
    },
    {
        "instrument": "Harp",
        "description": "Harp player"
    },
    {
        "instrument": "Harmonium",
        "description": "Harmonium player"
    },
    {
        "instrument": "Accordion",
        "description": "Accordion player"
    },
    {
        "instrument": "Bass guitar",
        "description": "Bass guitar player"
    },
    {
        "instrument": "Acoustic guitar",
        "description": "Acoustic guitar player"
    },
    {
        "instrument": "Saxophone",
        "description": "Saxophone player"
    }

]

music_jams = [
    "New Years Jam",
    "German Unification day Jam",
    "Mothers Day Jam",
    "Saint patric Day Jam",
]


def populate(apps, schema_editor):
    music_roles = [MusicRole.objects.create(**role) for role in roles]
    host = User.objects.get(email=os.environ.get('defaul_superuser_username', 'admin@admin.com'))
    for description in music_jams:
        music_jam = MusicJam.objects.create(description=description, host=host)
        for role in  random.sample(music_roles, random.randint(0, len(music_roles))):
            MusicJamRole.objects.create(music_jam=music_jam, role=role)




def reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("jams", "0002_create_defaul_user"),
    ]

    operations = [migrations.RunPython(populate, reverse)]
